"""Explainable scoring of how machine-like a text reads."""

from .calibrate import (
    BANDS,
    DEFAULT_CONFIDENCE,
    Band,
    Contribution,
    Score,
    score,
    score_features,
)
from .explain import MAGNITUDES, Explanation, Magnitude, Reason, explain
from .features import (
    DISCOURSE_MARKERS,
    FEATURE_SPECS,
    FEATURES,
    FIRST_PERSON_WORDS,
    FUNCTION_WORDS,
    Feature,
    FeatureSet,
    FeatureSpec,
    extract_features,
)
from .guard import (
    ARTICLES,
    CAUTIONS,
    FORMAL_CONNECTIVES,
    SIGNALS,
    TRANSFER_PATTERNS,
    UNEXAMINED,
    Caution,
    Guard,
    Reading,
    Signal,
    inspect_language,
)
from .reference import REFERENCE_INDEX, REFERENCE_NOTE, REFERENCES, Reference
from .segment import (
    Line,
    LineKind,
    Span,
    split_lines,
    split_paragraphs,
    split_sentences,
    split_words,
)

__all__ = [
    "ARTICLES",
    "BANDS",
    "CAUTIONS",
    "DEFAULT_CONFIDENCE",
    "DISCOURSE_MARKERS",
    "FEATURES",
    "FEATURE_SPECS",
    "FIRST_PERSON_WORDS",
    "FORMAL_CONNECTIVES",
    "FUNCTION_WORDS",
    "MAGNITUDES",
    "REFERENCES",
    "REFERENCE_INDEX",
    "REFERENCE_NOTE",
    "SIGNALS",
    "TRANSFER_PATTERNS",
    "UNEXAMINED",
    "Band",
    "Caution",
    "Contribution",
    "Explanation",
    "Feature",
    "FeatureSet",
    "FeatureSpec",
    "Guard",
    "Line",
    "LineKind",
    "Magnitude",
    "Reading",
    "Reason",
    "Reference",
    "Score",
    "Signal",
    "Span",
    "__version__",
    "explain",
    "extract_features",
    "inspect_language",
    "score",
    "score_features",
    "split_lines",
    "split_paragraphs",
    "split_sentences",
    "split_words",
]

__version__ = "0.0.1"
